on: push

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.2
        with:
          java-version: 17
          distribution: adopt
      - name: Maven CI
        run: mvn package
      - name: Upload a Client artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: packet-client
          path: packet-client/target/*.jar
      - name: Upload a Server artifact
        uses: actions/upload-artifact@v4.3.6
        with:
          name: packet-server
          path: packet-server/target/*.jar
                

